#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEE926C2BDACC177B (fabiano@fidencio.org)
#
Name     : libosinfo
Version  : 1.7.1
Release  : 16
URL      : https://releases.pagure.org/libosinfo/libosinfo-1.7.1.tar.xz
Source0  : https://releases.pagure.org/libosinfo/libosinfo-1.7.1.tar.xz
Source1  : https://releases.pagure.org/libosinfo/libosinfo-1.7.1.tar.xz.asc
Summary  : A library for managing OS information for virtualization
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 LGPL-2.1+
Requires: libosinfo-bin = %{version}-%{release}
Requires: libosinfo-data = %{version}-%{release}
Requires: libosinfo-lib = %{version}-%{release}
Requires: libosinfo-license = %{version}-%{release}
Requires: libosinfo-locales = %{version}-%{release}
Requires: libosinfo-man = %{version}-%{release}
Requires: clr-hardware-files
BuildRequires : buildreq-meson
BuildRequires : clr-hardware-files
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : libsoup-dev
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxslt)
BuildRequires : vala-dev

%description
libosinfo is a library that allows virtualization provisioning tools to
determine the optimal device settings for a hypervisor/operating system
combination.

%package bin
Summary: bin components for the libosinfo package.
Group: Binaries
Requires: libosinfo-data = %{version}-%{release}
Requires: libosinfo-license = %{version}-%{release}

%description bin
bin components for the libosinfo package.


%package data
Summary: data components for the libosinfo package.
Group: Data

%description data
data components for the libosinfo package.


%package dev
Summary: dev components for the libosinfo package.
Group: Development
Requires: libosinfo-lib = %{version}-%{release}
Requires: libosinfo-bin = %{version}-%{release}
Requires: libosinfo-data = %{version}-%{release}
Provides: libosinfo-devel = %{version}-%{release}
Requires: libosinfo = %{version}-%{release}

%description dev
dev components for the libosinfo package.


%package doc
Summary: doc components for the libosinfo package.
Group: Documentation
Requires: libosinfo-man = %{version}-%{release}

%description doc
doc components for the libosinfo package.


%package lib
Summary: lib components for the libosinfo package.
Group: Libraries
Requires: libosinfo-data = %{version}-%{release}
Requires: libosinfo-license = %{version}-%{release}

%description lib
lib components for the libosinfo package.


%package license
Summary: license components for the libosinfo package.
Group: Default

%description license
license components for the libosinfo package.


%package locales
Summary: locales components for the libosinfo package.
Group: Default

%description locales
locales components for the libosinfo package.


%package man
Summary: man components for the libosinfo package.
Group: Default

%description man
man components for the libosinfo package.


%prep
%setup -q -n libosinfo-1.7.1
cd %{_builddir}/libosinfo-1.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586066297
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Denable-vala=enabled \
-Denable-tests=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libosinfo
cp %{_builddir}/libosinfo-1.7.1/COPYING %{buildroot}/usr/share/package-licenses/libosinfo/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/libosinfo-1.7.1/COPYING.LIB %{buildroot}/usr/share/package-licenses/libosinfo/01a6b4bf79aca9b556822601186afab86e8c4fbf
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libosinfo

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/osinfo-detect
/usr/bin/osinfo-install-script
/usr/bin/osinfo-query

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Libosinfo-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libosinfo-1.0.deps
/usr/share/vala/vapi/libosinfo-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libosinfo-1.0/osinfo/osinfo.h
/usr/include/libosinfo-1.0/osinfo/osinfo_avatar_format.h
/usr/include/libosinfo-1.0/osinfo/osinfo_datamap.h
/usr/include/libosinfo-1.0/osinfo/osinfo_datamaplist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_db.h
/usr/include/libosinfo-1.0/osinfo/osinfo_deployment.h
/usr/include/libosinfo-1.0/osinfo/osinfo_deploymentlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_device.h
/usr/include/libosinfo-1.0/osinfo/osinfo_device_driver.h
/usr/include/libosinfo-1.0/osinfo/osinfo_device_driverlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_devicelink.h
/usr/include/libosinfo-1.0/osinfo/osinfo_devicelinkfilter.h
/usr/include/libosinfo-1.0/osinfo/osinfo_devicelinklist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_devicelist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_entity.h
/usr/include/libosinfo-1.0/osinfo/osinfo_enum_types.h
/usr/include/libosinfo-1.0/osinfo/osinfo_filter.h
/usr/include/libosinfo-1.0/osinfo/osinfo_firmware.h
/usr/include/libosinfo-1.0/osinfo/osinfo_firmwarelist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_image.h
/usr/include/libosinfo-1.0/osinfo/osinfo_imagelist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_install_config.h
/usr/include/libosinfo-1.0/osinfo/osinfo_install_config_param.h
/usr/include/libosinfo-1.0/osinfo/osinfo_install_config_paramlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_install_script.h
/usr/include/libosinfo-1.0/osinfo/osinfo_install_scriptlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_list.h
/usr/include/libosinfo-1.0/osinfo/osinfo_loader.h
/usr/include/libosinfo-1.0/osinfo/osinfo_media.h
/usr/include/libosinfo-1.0/osinfo/osinfo_medialist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_os.h
/usr/include/libosinfo-1.0/osinfo/osinfo_os_variant.h
/usr/include/libosinfo-1.0/osinfo/osinfo_os_variantlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_oslist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_platform.h
/usr/include/libosinfo-1.0/osinfo/osinfo_platformlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_product.h
/usr/include/libosinfo-1.0/osinfo/osinfo_productfilter.h
/usr/include/libosinfo-1.0/osinfo/osinfo_productlist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_resources.h
/usr/include/libosinfo-1.0/osinfo/osinfo_resourceslist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_tree.h
/usr/include/libosinfo-1.0/osinfo/osinfo_treelist.h
/usr/include/libosinfo-1.0/osinfo/osinfo_version.h
/usr/lib64/libosinfo-1.0.so
/usr/lib64/pkgconfig/libosinfo-1.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/Libosinfo/Libosinfo-osinfo-enum-types.html
/usr/share/gtk-doc/html/Libosinfo/Libosinfo-osinfo-version.html
/usr/share/gtk-doc/html/Libosinfo/Libosinfo.devhelp2
/usr/share/gtk-doc/html/Libosinfo/OsinfoAvatarFormat.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDatamap.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDatamapList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDb.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeployment.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeploymentList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDevice.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceDriver.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceDriverList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceLink.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceLinkFilter.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceLinkList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoDeviceList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoEntity.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoFilter.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoFirmware.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoFirmwareList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoImage.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoImageList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoInstallConfig.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoInstallConfigParam.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoInstallConfigParamList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoInstallScript.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoInstallScriptList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoLoader.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoMedia.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoMediaList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoOs.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoOsList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoOsVariant.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoOsVariantList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoPlatform.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoPlatformList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoProduct.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoProductFilter.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoProductList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoResources.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoResourcesList.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoTree.html
/usr/share/gtk-doc/html/Libosinfo/OsinfoTreeList.html
/usr/share/gtk-doc/html/Libosinfo/annotation-glossary.html
/usr/share/gtk-doc/html/Libosinfo/api-index-full.html
/usr/share/gtk-doc/html/Libosinfo/ch01.html
/usr/share/gtk-doc/html/Libosinfo/depr-index.html
/usr/share/gtk-doc/html/Libosinfo/home.png
/usr/share/gtk-doc/html/Libosinfo/index.html
/usr/share/gtk-doc/html/Libosinfo/left-insensitive.png
/usr/share/gtk-doc/html/Libosinfo/left.png
/usr/share/gtk-doc/html/Libosinfo/object-tree.html
/usr/share/gtk-doc/html/Libosinfo/right-insensitive.png
/usr/share/gtk-doc/html/Libosinfo/right.png
/usr/share/gtk-doc/html/Libosinfo/style.css
/usr/share/gtk-doc/html/Libosinfo/up-insensitive.png
/usr/share/gtk-doc/html/Libosinfo/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libosinfo-1.0.so.0
/usr/lib64/libosinfo-1.0.so.0.1007.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libosinfo/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libosinfo/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/osinfo-detect.1
/usr/share/man/man1/osinfo-install-script.1
/usr/share/man/man1/osinfo-query.1

%files locales -f libosinfo.lang
%defattr(-,root,root,-)

